stages:
  - analyze
  - test
  - build

flutter-analyze:
  stage: analyze
  image: cirrusci/flutter:stable
  script:
    - flutter pub get
    - flutter analyze

flutter-test:
  stage: test
  image: cirrusci/flutter:stable
  script:
    - flutter pub get
    - flutter test --coverage

flutter-build-android:
  stage: build
  image: cirrusci/flutter:stable
  script:
    - flutter pub get
    - flutter build apk --release
  artifacts:
    paths:
      - build/app/outputs/apk/release/
